project_name: oci-tool

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w

gomod:
  proxy: true

checksum:
  name_template: "checksums.txt"

source:
  enabled: true
